function z=DEMUX4WAY(in,s0,s1)
a=ANDFUNCTION(ANDFUNCTION(NOTFUNCTION(s0),NOTFUNCTION(s1)),in);
b=ANDFUNCTION(ANDFUNCTION(s0,NOTFUNCTION(s1)),in);
c=ANDFUNCTION(ANDFUNCTION(NOTFUNCTION(s0),s1),in);
d=ANDFUNCTION(ANDFUNCTION(s0,s1),in);
z=[a b c d];
end