function z=MUX4WAY(a,b,c,d,s0,s1)
x1=ANDFUNCTION(s1,s0);
x2=ANDFUNCTION(s1,NOTFUNCTION(s0));
x3=ANDFUNCTION(NOTFUNCTION(s1),s0);
x4=ANDFUNCTION(NOTFUNCTION(s1),NOTFUNCTION(s0));
y1=ORFUNCTION(ORFUNCTION(ORFUNCTION(ANDFUNCTION(a,x1),ANDFUNCTION(b,x2)),ANDFUNCTION(c,x3)),ANDFUNCTION(d,x4));
z=y1;
end